[package]
name = "iso-orphan"
version = "0.0.3"
authors = ["alejandrogzi <alejandrxgzi@gmail.com>"]
description = "detect orphan reads in isoseq data"
license.workspace = true
edition.workspace = true

[dependencies]
dashmap.workspace = true
rayon.workspace = true
log.workspace = true
clap.workspace = true
num_cpus.workspace = true
simple_logger.workspace = true
genepred.workspace = true
packbed.workspace = true
