[project]
name = "iso-classify"
version = "0.0.1"
description = "iso-classify local environment"
authors = [
    { name = "Alejandro Gonzales-Irribarren", email = "alejandrxgzi@gmail.com" },
]
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.10,<3.13"

dependencies = [
    "numpy>=1.19.0",
    "scikit-learn>=0.22,<2.0",
    "matplotlib==3.9.2",
    "scipy>=1.5.0",
    "biogl",
    "intronIC@git+https://github.com/alejandrogzi/intronIC",
    "setuptools",
]
